import './style.css';
const navHeader = require('../images/nav-header.png');
const bread01 = require('../images/bread01.png');
const bread02 = require('../images/bread02.png');
const bread03 = require('../images/bread03.png');
const bread04 = require('../images/bread04.png');
const bread05 = require('../images/bread05.png');
const bread06 = require('../images/bread06.png');
const bread07 = require('../images/bread07.png');
const bread08 = require('../images/bread08.png');

document.getElementById('navHeader').innerHTML = `<img src="${navHeader}" alt="header nav" />`;
document.getElementById('bread01').innerHTML = `<img src="${bread01}" />`;
document.getElementById('bread02').innerHTML = `<img src="${bread02}" />`;
document.getElementById('bread03').innerHTML = `<img src="${bread03}" />`;
document.getElementById('bread04').innerHTML = `<img src="${bread04}" />`;
document.getElementById('bread05').innerHTML = `<img src="${bread05}" />`;
document.getElementById('bread06').innerHTML = `<img src="${bread06}" />`;
document.getElementById('bread07').innerHTML = `<img src="${bread07}" />`;
document.getElementById('bread08').innerHTML = `<img src="${bread08}" />`;